name: Discord Notification

on:
  schedule:
    - cron: "47 20 * * *"  # Example: Runs at 8:10 PM UTC (2:40 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install requests

    - name: Run Python Script
      run: python discord_notification.py
